Recheck DOCKER_USER and DOCKER_PASS before deploy
This commit will recheck 2 prerequisite variables: DOCKER_USER and DOCKER_PASS
before push to dockerhub.

In order to set up deployment correctly, you have to set those in CircleCI
project's environment variables.
By default, these images will push into docker user's own repository but you can
change repository name by setting REPO_NAME variable.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,10 +53,21 @@ jobs:
           name: Build docker images
           command: |
             cd docker
+            REPO_NAME=${REPO_NAME:-$DOCKER_USER}
+            DOCKER_TAG=${DOCKER_TAG:-latest}
             ./build.sh
       - run:
           name: Push to docker hub
           command: |
+            if [ ! "$DOCKER_USER"  -o  ! "$DOCKER_PASS"  ]
+            then
+              echo "Missing required environment variables"
+              echo "- DOCKER_USER"
+              echo "- DOCKER_PASS"
+              exit 1
+            fi
+            REPO_NAME=${REPO_NAME:-$DOCKER_USER}
+            DOCKER_TAG=${DOCKER_TAG:-latest}
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker push $REPO_NAME/abci:$DOCKER_TAG
             docker push $REPO_NAME/tendermint:$DOCKER_TAG
